server:
  port: 8080
  tomcat:
    threads.max: 300
    max-connections: 8192
  servlet:
    session:
      timeout: 500ms
  jetty:
    connection-idle-timeout: 5000ms
    threads:
      idle-timeout: 5000ms
spring:
  application:
    name: CATALOG-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/catalogdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 400
      connection-timeout: 5000
      idle-timeout: 5000
      max-lifetime: 5000
    tomcat:
      max-active: 2000
      max-wait: 5000
  mvc:
    async:
      request-timeout: 10000ms

  jpa:
    generate-ddl: true
    show-sql: false


#  flyway:
#    url: jdbc:postgresql://localhost/catalogDB
#    user: postgres
#    password: postgres
#    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui

