spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
          filters:
            - AuthenticationFilter

        - id: shop-order-service
          uri: lb://SHOP-ORDER-SERVICE
          predicates:
            - Path=/shop-order/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**

  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

signKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
