server:
  port: 8080
spring:
  application:
    name: CATALOG-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/catalogdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  aop:
    proxy-target-class: true
  jpa:
    generate-ddl: true
    show-sql: false
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui