spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/identity
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  signKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 180000
