spring:
  application:
    name: SHOP-CART-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:6666/shop-cartDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:6666/shop-cartDB
    user: postgres
    password: postgres
    locations: classpath:db/migration

server:
  port: 8003

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

signKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

catalog-api: http://localhost:8888/
