version: "3"
services:
  store-ui:
    build: .
    ports:
      - "4200:4200"
    volumes:
        - "/app/node_modules"
        - "./src:/app"
    networks:
      - store

networks:
  store:
    external: true
